---
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'prettier'
  - 'plugin:prettier/recommended'
plugins:
  - node
  - prettier
rules:
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-var: error
  prefer-const: error
  object-curly-spacing: off
