---
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'prettier'
  - 'plugin:prettier/recommended'
plugins:
  - node
  - prettier
rules:
  possibleErrors:
    eqeqeq: error
  bestPractices:
    block-scoped-var: error
    no-warning-comments: warn
  variables:
    no-var: error
    prefer-const: error
  stylisticIssues:
    object-curly-spacing: off
  plugins:
    prettier/prettier: error
